### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by yonatandt** [meateam/web-ui#6]
The UI should display the user's name.

**Comment by LiorHaim** [comment]
Any progress?

**Comment by omrishtam** [comment]
> Any progress?

This issue depends on [api-gateway's authentication](https://github.com/meateam/api-gateway/issues/6).
We closed that issue after merging [the feature for it](https://github.com/meateam/api-gateway/pull/15) which broke all routes in the api-gateway since the feature depended on other services which were not configured, so we reverted the merge and reopened the issue shortly after.

**Comment by omrishtam** [comment]
@LiorHaim done in #24
